var ZCSDK=new function(){var b=!1,c,e=void 0,d={};this._init=function(){if(!b){b=!0;c=new ZSDK;d.appSDK=c;var a;e=new Promise(function(b,h){a=b});c.OnLoad(function(){c.getContext().Event.Trigger("GET_INIT_PARAMS",!0,!0).then(function(b){d.initParams=b;c.getContext().Event.Trigger("GET_QUERY_PARAMS",!0,!0).then(function(b){d.queryParams=b;a()})})})}return e};this._getInitParams=function(){return d.initParams};this._getQueryParams=function(){return d.queryParams};this._getApi=function(){return{API:{RECORDS:new Records(d)},
UTIL:new Util(d)}}},ZOHO=new function(){var b=!1,c,e=void 0,d={};return{CREATOR:{API:new Records(d),UTIL:new Util(d),init:function(){if(!b){b=!0;c=new ZSDK;d.appSDK=c;var a;e=new Promise(function(b,h){a=b});c.OnLoad(function(){c.getContext().Event.Trigger("GET_INIT_PARAMS",!0,!0).then(function(b){d.initParams=b;c.getContext().Event.Trigger("GET_QUERY_PARAMS",!0,!0).then(function(b){d.queryParams=b;a()})})})}return e}}}};
function Records(b){function c(a){a.scope||(a.scope=b.initParams.scope);a.appName||(a.appName=b.initParams.appName)}function e(a,b){var h=!1,d;for(d in a){var c;if(c=!(b&&b.includes(d))){c=a[d];var n=!1,f;if(!(f=!c||null==c||""===c||"string"==typeof c&&0==c.trim().length)&&(f="object"==typeof c))a:{f=void 0;for(f in c){f=!1;break a}f=!0}f&&(n=!0);c=n}c&&(h=!0)}return h}function d(a){return new Promise(function(b,h){var c=new FileReader;c.readAsDataURL(a);c.onload=function(){b(c.result)};c.onerror=
function(a){h(a)}})}return{addRecord:function(a){if(e(a))return new Promise(function(a,b){b("Improper Configuration..!!")});c(a);a={formLinkName:a.formName,body:a.data};return b.appSDK.getContext().Event.Trigger("ADD_RECORD",a,!0)},updateRecord:function(a){if(e(a))return new Promise(function(a,b){b("Improper Configuration..!!")});var d=a.id.toString().split(",");c(a);a={viewLinkName:a.reportName,body:a.data,listOfRecords:d};return b.appSDK.getContext().Event.Trigger("EDIT_RECORDS",a,!0)},deleteRecord:function(a){if(e(a))return new Promise(function(a,
b){b("Improper Configuration..!!")});c(a);a={viewLinkName:a.reportName,criteria:a.criteria};return b.appSDK.getContext().Event.Trigger("DELETE_RECORDS",a,!0)},getRecordById:function(a){if(e(a))return new Promise(function(a,b){b("Improper Configuration..!!")});c(a);a={viewLinkName:a.reportName,id:a.id};return b.appSDK.getContext().Event.Trigger("GET_RECORD",a,!0)},getAllRecords:function(a){if(e(a,["criteria","page","pageSize"]))return new Promise(function(a,b){b("Improper Configuration..!!")});c(a);
a={viewLinkName:a.reportName,criteria:a.criteria,page:a.page,pageSize:a.pageSize};return b.appSDK.getContext().Event.Trigger("GET_RECORDS",a,!0)},uploadFile:function(a){if(e(a,["file","parentId"]))return new Promise(function(a,b){b("Improper Configuration..!!")});c(a);return a.file?a.file.size&&50<a.file.size/1024/1024?new Promise(function(a,b){b("Improper Configuration..!!")}):new Promise(function(c,h){var e=d(a.file),n="",q=a.file.name;e.then(function(d){n=d;d={viewLinkName:a.reportName,id:a.id,
fieldName:a.fieldName,file:n,fileName:q};a.parentId&&(d.parentId=a.parentId);b.appSDK.getContext().Event.Trigger("UPLOAD_FILE",d,!0).then(function(a){c(a)}).catch(function(a){h(a)})}).catch(function(a){h(a)})}):new Promise(function(a,b){b("Improper Configuration..!!")})}}}
function Util(b){return{setImageData:function(c,e){var d={};d.src=e;b.appSDK.getContext().Event.Trigger("IMAGE_LOAD",d,!0).then(function(a){c.setAttribute("src",a)})},getInitParams:function(){return b.initParams},getQueryParams:function(){return b.queryParams}}};function ZSDK(){function b(){return"function"!=typeof u?void w.Error("No OnLoad Handler provided to execute."):A?void w.Error("OnLoad event already triggered."):(u.call(l,l),void(A=!0))}function c(){p.call(l,l)}function e(){return y}function d(a,b,c){return ZSDKMessageManager.TriggerEvent(a,b,c)}function a(a){w.Info("Setting AppContext data");var b=a&&a.model||{};a&&a.locale;a&&a.localeResource;if(isDevMode&&a.locale&&a.localeResource&&0===Object.keys(a.localeResource).length&&a.localeResource.constructor===
Object&&a.locale&&r(a.locale),"undefined"!=typeof ZSDKModelManager){for(var B in b)ZSDKModelManager.AddModel(B,b[B]);l.Model=ZSDKModelManager.GetModelStore()}g=a.uniqueID;k=a.connectors;w.Info("App Connectors ",k);y=!0}function n(){return g}function h(a){}function v(){return k}function r(a){q("/app-translations/"+a+".json",function(a){z=JSON.parse(a);x()})}function q(a,b){var c=new XMLHttpRequest;c.open("GET",a,!1);c.onreadystatechange=function(){4==c.readyState&&"200"==c.status&&b(c.responseText)};
c.send(null)}function f(a,b,c){for(var d="";d!=a;)d=a,a=a.replace(b,c);return a}function t(a,b){b=b.replace(/\[(\w+)\]/g,".$1");b=b.replace(/^\./,"");b=b.split(".");for(var c=0,d=b.length;c<d;++c){var m=b[c];if(!(m in a))return;a=a[m]}return a}function x(){var a=document.querySelectorAll("[data-i18n]"),b;for(b in a)if(a.hasOwnProperty(b)){var c=t(z,a[b].getAttribute("data-i18n"));if(!c)return!1;if(a[b].hasAttribute("data-options")){var d=JSON.parse(JSON.stringify(eval("("+a[b].getAttribute("data-options")+
")"))),m=Object.keys(d),g;for(g in m)c=f(c,"${"+m[g]+"}",d[m[g]])}a[b].innerHTML=c}}var u,p,k,m,g,z={},w=ZSDKUtil.getLogger(),y=!1,A=!1;this.isContextReady=!1;this.HelperContext={};this.isDevMode=!1;this.getContext=function(){return l};var l={Model:{},Event:{}};l.Event.Listen=function(a,b){ZSDKEventManager.AttachEventListener(a,b)};l.Event.Trigger=d;l.GetRequest=function(a){return ZSDKMessageManager.SendRequest(a)};l.QueryParams=m;l.Translate=function(a,b){var c="";if(a&&(c=t(z,a)),!c)return!1;if(b){b=
JSON.parse(JSON.stringify(eval(b)));var d=Object.keys(b);for(a in d)c=f(c,"${"+d[a]+"}",b[d[a]])}return c};this.OnLoad=function(a){if("function"!=typeof a)throw Error("Invalid Function value is passed");u=a;y&&b()};this.OnUnLoad=function(a){};this.OnContextUpdate=function(a){p=a};(function(){m=ZSDKUtil.GetQueryParams();isDevMode=!!m.isDevMode;var g={};g.isDevMode=isDevMode;g.ExecuteLoadHandler=b;g.SetContext=a;g.UpdateContext=h;g.QueryParams=m;g.GetConnectors=v;g.TriggerEvent=d;g.ExecuteContextUpdateHandler=
c;g.getUniqueID=n;g.isAppRegistered=e;var f=ZSDKMessageManager.Init(g);window.addEventListener("message",f);window.addEventListener("unload",function(){ZSDKMessageManager.DERegisterApp()});"undefined"!=typeof ZSDKModelManager&&ZSDKModelManager.Init(g);ZSDKMessageManager.RegisterApp()})()}
var ZSDKUtil=function(b){function c(a){}function e(a){var b={};return a=a||window.location.href,a.substr(a.indexOf("?")+1).split("\x26").forEach(function(a,c){a=a.split("\x3d");b[a[0]]=a[1]}),b.hasOwnProperty("serviceOrigin")&&(b.serviceOrigin=decodeURIComponent(b.serviceOrigin)),b}var d,a=e();return c.prototype.Info=function(){(b.isDevMode()||b.isLogEnabled())&&window.console.info.apply(null,arguments)},c.prototype.Error=function(){(b.isDevMode()||b.isLogEnabled())&&window.console.error.apply(null,
arguments)},b.GetQueryParams=e,b.isDevMode=function(){return a&&a.isDevMode},b.isLogEnabled=function(){return a&&a.isLogEnabled},b.getLogger=function(){return d&&d instanceof c||(d=new c),d},b.Sleep=function(a){for(var b=(new Date).getTime();b+a>(new Date).getTime(););},b}(window.ZSDKUtil||{}),ZSDKMessageManager=function(b){function c(b){try{var c="string"==typeof b.data?JSON.parse(b.data):b.data}catch(C){c=b.data}var m=c.type,h=c.eventName;try{var k;if(!(k="SET_CONTEXT"===h)){var q=b.source,l=b.origin;
k=!(!f.isAppRegistered()||t!==q||x!==l)||Error("Un-Authorized Message.")}if(k)switch(m){case "FRAMEWORK.EVENT":var r=(c.data,c.eventName),p={SET_CONTEXT:e,UPDATE_CONTEXT:d,EVENT_RESPONSE:a,EVENT_RESPONSE_FAILURE:n}[r];p&&"function"==typeof p?p(b,c):ZSDKEventManager.NotifyEventListeners(f.AppContext,c.eventName,c.data);break;default:f.MessageInterceptor(b,c)}}catch(C){u.Error("[SDK.MessageHandler] \x3d\x3e ",C.stack)}}function e(a,b){a.origin;t=window.parent;x=f.QueryParams.serviceOrigin;f.SetContext(b.data);
f.ExecuteLoadHandler()}function d(a,b){}function a(a,b){h(b.promiseid,!0,b.data)}function n(a,b){h(b.promiseid,!1,b.data)}function h(a,b,c){k.hasOwnProperty(a)&&(b?k[a].resolve(c):k[a].reject(c),k[a]=void 0,delete k[a])}function v(a){return new Promise(function(b,c){k[a]={resolve:b,reject:c,time:(new Date).getTime()}})}function r(a){if("object"==typeof a&&(a.appOrigin=encodeURIComponent(q())),!t)throw Error("Parentwindow reference not found.");t.postMessage(a,f.QueryParams.serviceOrigin)}function q(){return window.location.protocol+
"//"+window.location.host+window.location.pathname}var f,t,x,u=ZSDKUtil.getLogger(),p=100,k={};/^https?:\/\/[a-zA-Z0-9-_]*.(csez.zohocorpin.com|zoho.com|zohoplatform.com|zohosandbox.com)(:[0-9]{0,4})?$/;return b.Init=function(a,d){if(!a||"object"!=typeof a)throw Error("Invalid Context object passed");if(d&&"object"!=typeof d)throw Error("Invalid Configuration Passed to MessageManager");return f=a,c.bind(b)},b.RegisterApp=function(){var a={type:"SDK.EVENT",eventName:"REGISTER",appOrigin:encodeURIComponent(q())};
window.top.postMessage(a,f.QueryParams.serviceOrigin)},b.DERegisterApp=function(){r({type:"SDK.EVENT",eventName:"DEREGISTER",uniqueID:f.getUniqueID()})},b.SendRequest=function(a){if(!a||"object"!=typeof a)throw Error("Invalid Options passed");var b="Promise"+p++;r({type:"SDK.EVENT",eventName:"HTTP_REQUEST",uniqueID:f.getUniqueID(),time:(new Date).getTime(),promiseid:b,data:a});a=v(b);return a},b.TriggerEvent=function(a,b,c){if(!a)throw Error("Invalid Eventname : ",a);var d=c?"Promise"+p++:void 0;
if(r({type:"SDK.EVENT",eventName:a,uniqueID:f.getUniqueID(),time:(new Date).getTime(),promiseid:d,data:b}),c)return v(d)},b}(window.ZSDKMessageManager||{}),ZSDKEventManager=function(b){var c=ZSDKUtil.getLogger(),e={};return b.AttachEventListener=function(b,a){"function"==typeof a&&(Array.isArray(e[b])||(e[b]=[]),e[b].push(a))},b.NotifyEventListeners=function(b,a,n){var d=a.match(/^__[A-Za-z_]+__$/gi);if((d=(Array.isArray(d)&&d.length,e[a]))&&Array.isArray(d))for(a=0;a<d.length;a++)d[a].call(b,n);
else c.Info("Cannot find EventListeners for Event : ",a)},b.NotifyInternalEventHandler=function(b,a){var c=a.eventName;"__APP_INIT__"===c?(b.SetContext(a.data),b.ExecuteLoadHandler()):"__APP_CONTEXT_UPDATE__"===c&&(b.UpdateContext(a.data),b.ExecuteContextUpdateHandler())},b}(window.ZSDKEventManager||{});